ALTER TABLE "TeamDevice" ADD COLUMN "displayName" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Competition" ADD COLUMN "details" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Competition" ADD COLUMN "startsAt" DATETIME;
ALTER TABLE "Competition" ADD COLUMN "endsAt" DATETIME;
ALTER TABLE "Competition" ADD COLUMN "qrCode" TEXT;
ALTER TABLE "Competition" ADD COLUMN "requiresQr" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Competition" ADD COLUMN "questionCount" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Competition" ADD COLUMN "leaderboardVisible" BOOLEAN NOT NULL DEFAULT false;
CREATE UNIQUE INDEX "Competition_qrCode_key" ON "Competition"("qrCode");

ALTER TABLE "Question" ADD COLUMN "category" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Question" ADD COLUMN "questionType" TEXT NOT NULL DEFAULT 'text';
ALTER TABLE "Question" ADD COLUMN "mediaUrl" TEXT;
ALTER TABLE "Question" ADD COLUMN "mediaAlt" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Score" ADD COLUMN "attemptedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Score" ADD COLUMN "correctCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Score" ADD COLUMN "questionCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Score" ADD COLUMN "completedAll" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "QuizSession" ADD COLUMN "questionOrder" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "QuizSession" ADD COLUMN "lastAnswerAt" DATETIME;
ALTER TABLE "QuizSession" ADD COLUMN "attemptedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "QuizSession" ADD COLUMN "correctCount" INTEGER NOT NULL DEFAULT 0;
